### ISSUE TITLE
php artisan schedule:summary Args/Opts column is blank?

### ISSUE THREAD

**Issue by MarkVaughn** [Indatus/dispatcher#131]
Laravel 4 when I look at the summary, I have 6 commands and for all of them the Args/Opts column appears blank
example of a schedule

```
        return $scheduler->everyMinutes(3)->opts(['l'=>1000]);
```

Shouldn't that be populated in the list?

**Comment by bkuhl** [comment]
`opts()` / `args()` need to be called prior to any scheduling... see https://github.com/Indatus/dispatcher#advanced-scheduling

**Comment by MarkVaughn** [comment]
OK I switched the order, still the column is blank (why close tickets before verifying they are resolved?)
````
 return $scheduler->opts(['l'=>1000])->everyMinutes(3);
````

**Comment by bkuhl** [comment]
Can you show the output of `artisan scheduled:summary` here?

The ticket was closed because sometimes requesters don't come back to verify the issue is resolved and they can always be reopened.

**Comment by MarkVaughn** [comment]
`````
+----------------+-------------------------+-----------+--------+------+--------------+-------+-------------+--------+
| Environment(s) | Name                    | Args/Opts | Minute | Hour | Day of Month | Month | Day of Week | Run as |
+----------------+-------------------------+-----------+--------+------+--------------+-------+-------------+--------+
| *              | email:reports           |           | 0      | 6    | *            | *     | *           |        |
| *              | position:process        |           | */3    | *    | *            | *     | *           |        |
| *              | shift:calculate         |           | 0      | 4    | *            | *     | *           |        |
| *              | database:backup         |           | 0      | 2    | *            | *     | *           |        |
| *              | tables:check            |           | *      | *    | *            | *     | *           |        |
| *              | service:receipts        |           | 0      | 1    | *            | *     | *           |        |
| *              | service:generate-blanks |           | 0      | *    | *            | *     | *           |        |
+----------------+-------------------------+-----------+--------+------+--------------+-------+-------------+--------+
````

three should have options

**Comment by MarkVaughn** [comment]
as I was using the short name for options i changed
````
        return $scheduler->opts(['s'])->daily()->hours(2);
//to
        return $scheduler->opts(['skip'])->daily()->hours(2);
````

**Comment by bkuhl** [comment]
I didn't realize the requester couldn't reopen the issue... I'll avoid closing in the future.

I'm unsure if your last comment means you resolved the issue, are you saying you've resolved it by using the long option name instead of the short option name?

If not, can you please try using this exact code and paste the `scheduled:summary` output?  Which version of Dispatcher and Laravel are you using?

   public function schedule(Schedulable $scheduler)
    {
        return  $scheduler->opts([
                    'force',
                    'toDelete' => 'expired',
                    'exclude' => [
                        'admins',
                        'developers'
                    ]
                ])
                ->minutes(3);
    }
```

Using the above command, it should be clear whether Dispatcher is interpreting the options correctly.

**Comment by MarkVaughn** [comment]
I didn't resolve it by using the long name, but I tried it to make sure that wasn't it.

I copy pasted that example and the column is still blank.

Regarding the version copied from my composer.json
````
    "laravel/framework": "4.2.*",
    "indatus/dispatcher": "~1.4",
````

**Comment by bkuhl** [comment]
Looks like it's an issue within the `scheduled:summary` command.  To give my assumption a quick test... can you update the schedule method to `return [$scheduler->opts(['l'=>1000])->everyMinutes(3)];`?  It looks like the way it prints the summary, if a single schedule is returned it doesn't show options/arguments.

**Comment by MarkVaughn** [comment]
@bkuhl yup that fixed it to display it 
````
+----------------+-------------------------+------------------------------+--------+------+--------------+-------+-------------+--------+
| Environment(s) | Name                    | Args/Opts                    | Minute | Hour | Day of Month | Month | Day of Week | Run as |
+----------------+-------------------------+------------------------------+--------+------+--------------+-------+-------------+--------+
| *              | email:reports           |                              | 0      | 6    | *            | *     | *           |        |
| *              | position:process        |                              |        |      |              |       |             |        |
|                |                         | --l="1000" --env="homestead" | */3    | *    | *            | *     | *           |        |
| *              | shift:calculate         |                              | 0      | 4    | *            | *     | *           |        |
| *              | database:backup         |                              |        |      |              |       |             |        |
|                |                         | --skip --env="homestead"     | 0      | 2    | *            | *     | *           |        |
| *              | tables:check            |                              | *      | *    | *            | *     | *           |        |
| *              | service:receipts        |                              | 0      | 1    | *            | *     | *           |        |
| *              | service:generate-blanks |                              | 0      | *    | *            | *     | *           |        |
+----------------+-------------------------+------------------------------+--------+------+--------------+-------+-------------+--------+
````
as you see it created an unnecessary row (probably to the array nature)
I also managed confirmed my suspicion that dispatcher does not recognize short names for options.
I appreciate your time and all the help you provided in figuring these things out. Here are three 
things that could be done as a result from our correspondence

1. display options in summary when scheduler is passed back directly (not as array)
2. update the note in the documentation that the order is important (i.e call opts before any time parameters, currently it just describes that opts causes a new instance people might not realize the implications) 
3. either note that the short forms of options is not accepted in the opts method or update the code to recognize short names for options

Thanks again
